select * from client_master where name like '_a%' ;
select * from client_master where city like 'm%' ;
select * from client_master where city in ('Bombay','delhi');
select * from client_master where baldue>10000 ;
select * from sales_order where orderdate  like '%_6_%' ;
select * from client_master where clientno in('C00001','C00002');
select * from product_master where sellprice>500 and sellprice<=750;
alter table product_master add column new_price numeric;
UPDATE product_master SET new_price= (sellprice*0.15)+sellprice WHERE sellprice>500;
select name,city,state from client_master where state not in ('maharashtra') ;
SELECT count(orderno) from sales_order; 
select avg(sellprice) from product_master;
select max(sellprice) as max_price,min(sellprice) as min_price from product_master;
SELECT count(productno) from product_master where sellprice<=500; 
SELECT  description from product_master where qtyonhand<recorderlvl;
